### ISSUE TITLE
Trouble getting an access token from WorldcatAccessToken()

### ISSUE THREAD

**Issue by johnjung** [BookOps-CAT/bookops-worldcat#62]
I'm having some trouble getting an access token from [WorldCatAccessToken()](https://github.com/BookOps-CAT/bookops-worldcat/blob/a74af30114a35ab90802e0865c9a090207231cb4/bookops_worldcat/authorize.py#L19) to query the Worldcat Search API. I see that the constructor accepts a few different parameters- I understand what key and secret are, but I'm not sure what kind of values to use for scopes, principal_id, and principal_idns. 

Is there a list of scopes I can refer to? And what should I use for principal_id and principal_idns? 

Thank you very much for any help you can provide- I appreciate it.

**Comment by klinga** [comment]
Apologies, @johnjung , I missed your inquiry (did not realize my notification have not been turned off!).

`bookops-worldcat` does not support anymore Worldcat Search API, only Wordcat Metadata API (dropped at v 0.3.0 due to OCLC changes). Your credentials for the Search API will not (most likely) work for Metadata API. Initially I had plans to restore and expand the Search API functionality, but I think the priority now is to upgrade it to Metadata API 2.0. Maybe someday in the future...

You could however request credentials for the Metadata API and use `bookops-worldcat` and the service's search endpoints to get data out of OCLC. See here: https://developer.api.oclc.org/wc-metadata-v2#/Search%20Bibliographic%20Resources/search-brief-bibs

When you requested MetadataAPI credentials from OCLC you should have received an email that includes some of the information required to interact with their services. That email does not include your key or secret, only other related info, including sandbox records numbers.
It should include something like that (copied from [their docs](https://www.oclc.org/developer/develop/authentication/user-level-authentication-and-authorization.en.html#:~:text=The%20principalID%20represents%20a%20user,the%20user%20is%20associated%20with.))

_Your Institution's Registry ID:
12345

Your Principal ID: 8eab9f92-3951-431c-975a-d7dfkd9rd131
Your principal IDNS: urn:oclc:wms:{registryID}_

For the principal_idns, simply replace registryID in the number given in your email.

Let me know if you need more help.
Cheers!

**Comment by johnjung** [comment]
Thank you very much- this is very helpful, and I really appreciate it.

Thanks again!
